<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'languages'=>[
        'ar-SY' => 'العربية',
        'en-US' => 'English'
    ],
    'gender' =>  Yii::t('app','gender'),
    'Husband'=> Yii::t('app','Husband'),
    'Wives'=> Yii::t('app','Wives'),
    'Sons'=> Yii::t('app','Sons'),
    'Daughters'=> Yii::t('app','Daughters'),
    'Grandsons'=>Yii::t('app','Grandsons'),
    'Granddaughters'=> Yii::t('app','Granddaughters'),
    'Father'=> Yii::t('app','Father'),
    'Mother'=> Yii::t('app','Mother'),
    'Grandfather'=> Yii::t('app','Grand father'),
    'PaternalGrandmother'=> Yii::t('app','Paternal Grandmother'),
    'MaternalGrandmother'=> Yii::t('app','Maternal Grandmother'),
    'FullBrothers'=> Yii::t('app','Full Brothers'),
    'FullSisters'=> Yii::t('app','Full Sisters'),
    'PaternalBrothers'=> Yii::t('app','Paternal Brothers'),
    'PaternalSisters'=> Yii::t('app','Paternal Sisters'),
    'MaternalBrothers'=> Yii::t('app','Maternal Brothers'),
    'MaternalSisters'=> Yii::t('app','Maternal Sisters'),
    'FullNephews'=> Yii::t('app','Full Nephews'),
    'PaternalNephews'=> Yii::t('app','Paternal Nephews'),
    'FullUncles'=> Yii::t('app','Full Uncles'),
    'PaternalUncles'=> Yii::t('app','Paternal Uncles'),
    'FullCousins'=> Yii::t('app','Full Cousins'),
    'PaternalCousins'=> Yii::t('app','Paternal Cousins'),
];
